title: COMP-2913 React & Modern JavaScript
description: British Columbia Institute of Technology - School of Computing and Academic Studies
author: Daniel K. Takeuchi
github: https://github.com/daniel-takeuchi
about: Instructor @ BCIT
disqus_shortname: comp2913
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/summonagus"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://daniel-takeuchi.github.io/COMP-2913/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
